image: node:18-bookworm

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables: # goofy thing where you have to manually inherit secrets/variables from the UI
  SSH_KEY: $SECRET_SSH_KEY
  SSH_HOST: "www.xhec.dev"
  SSH_USER: "root"
  DEPLOY_PATH: "/var/www/xhecdev/"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  artifacts:
    paths: 
        - build/
  script:
    - echo "Compiling the code..."
    - make build
    - echo "Compile complete."

deploy-job:
  stage: deploy
  inherit:
    variables: true
  script:
    - mkdir ~/.ssh
    - echo "Creating SSH key"
    - |
      cat >> ~/.ssh/config << EOF
      Host *
        StrictHostKeyChecking no
      EOF
    - cp $SECRET_SSH_KEY ~/.ssh/id_rsa.pub
    - echo "Installing rsync"
    - apt update && apt install rsync -y
    - echo "Pushing to $SSH_HOST at $DEPLOY_PATH"
    - rsync -avc build/* $SSH_USER@$SSH_HOST:$DEPLOY_PATH/.