image: node:18-bookworm

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables: # goofy thing where you have to manually inherit secrets/variables from the UI
  SSH_KEY: $SECRET_SSH_KEY
  SSH_HOST: "www.xhec.dev"
  SSH_USER: "root"
  DEPLOY_PATH: "/var/www/xhecdev/"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  artifacts:
    paths: 
        - build/
  script:
    - echo "Running build"
    - make build
    - echo "Build complete."

deploy-job:
  stage: deploy
  only:
    - main
  inherit:
    variables: true
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - cp $SECRET_SSH_KEY ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - echo "Installing rsync"
    - apt update && apt install rsync -y
    - echo "Pushing to $SSH_HOST at $DEPLOY_PATH"
    - rsync -avc build/* $SSH_USER@$SSH_HOST:$DEPLOY_PATH/.