image: node:18-bookworm

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  artifacts: 
    paths: 
        - build/
  script:
    - echo "Compiling the code..."
    - make build
    - echo "Compile complete."

deploy-job:
  stage: deploy
  script:
    - echo $SSH_KEY > .ssh/id_rsa.pub
    - apt update && apt install rsync -y
    - rsync -avc build/* $SSH_USER@$SSH_HOST:$DEPLOY_PATH/.