on: [push]
jobs:
  testforpush:
    runs-on: docker
    container:
        image: node:20.11.1-buster-slim
    steps:
      - run: apt update && apt install make git -y
      - uses: actions/checkout@v4
      - run: make build
      - run: echo "profit"
