on:
  push:
    branches: [main]
jobs:
  testforpush:
    runs-on: docker
    container:
        image: node:18.19.1-buster-slim
    steps:
      - run: apt update && apt install make git -y
      - uses: actions/checkout@v4
      - run: make build
      - run: echo "profit"
