name: Build and Deploy the Website

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: debian
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/website
          git pull
          git checkout main
          git pull
          make deploy
          systemctl restart nginx

