name: Test build of website

on:
  push:
    branches:
      - 'experiment'
  pull_request:

jobs:
  tbuild:
    runs-on: debian
    steps:
    - name: Check out code
      uses: actions/checkout@v4
#    - name: Setup Node
#      uses: actions/setup-node@v3
#      with:
#        node-version: 18.17.1
    - name: Test Build
      run: |
        make build
