name: Test build of website

on: [push, pull_request]

jobs:
  tbuild:
    runs-on: debian
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Test Build
      run: make build
