name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get install ruby-full build-essential zlib1g-dev -y
    - run: sudo gem install jekyll bundler
    - run: bundle exec jekyll build
    - run: echo "done."