name: Build Website

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Do build
      run: make setup build
    - name: Deploy
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "build/*"
        target: /var/www/xhecdev/.
