name: Test Pull Request

on:
  pull_request:

jobs:
  testforpush:
    runs-on: ubuntu-latest
    container:
      image: node:20.15.0-buster-slim
    steps:
      - name: Check if push workflow ran
        id: check_push_status
        run: |
          if [ -f .github/workflows/status/push_status.txt ]; then
            echo "Push workflow already ran. Skipping PR test build."
            exit 0
          fi
    
      - name: Update and install dependencies
        run: |
          apt update && apt install make git -y
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build the project
        run: make build
        
      - name: Echo profit
        run: echo "profit"
