name: Test build of website

on: [pull_request, push]

jobs:
  tbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
    - name: Test Build
      run: |
        make build
        - name: Open Pull Request
          run: |
            # Use the GitHub Actions API or a GitHub CLI command to create the pull request
            # Specify the branch names and any necessary details for the pull request