name: Test build of website

on: [pull_request, push]

jobs:
  tbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
    - name: Test Build
      run: |
        make build